[project]
name = "langdev2025-spacetimepy-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "spacetimepy[debug,game,web]",
]

[tool.uv.sources]
spacetimepy = { path = "../PyMonitor", editable = true }
